---
new_page_extension: md
auto_deploy: false
admin_path: "/static/admin"
webhook_url: 
sections:
- type: document
  path: content/sobre.md
  label: Sobre
  templates:
  - sobre
- type: document
  path: content/financiamento.md
  label: Financiamento
  templates:
  - sobre
- type: directory
  path: content/carros
  label: Veículos
  create: all
  match: "**/*"
  new_doc_ext: json
  templates:
  - veiculos
- type: directory
  path: content/artigos
  label: Artigos
  create: all
  match: "**/*"
  new_doc_ext: md
  templates:
  - blog
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
